/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "collectionsoverview": [],
    "search": [],
    "about": [],
    "books.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "books.sequence": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "sequence",
            "required": true
        }
    ],
    "browse": [],
    "partners": [],
    "providers": [],
    "providers.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "subjects": [],
    "subjects.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "series": [],
    "series.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
