#
# Site directory
#
<Directory /usr/local/apache2/htdocs/ancientworld>
  DirectoryIndex index.html
  Order allow,deny
  Allow from all
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^ - [E=protossl]
    RewriteCond %{HTTPS} on
    RewriteRule ^ - [E=protossl:s]
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule "(^|/)\." - [F]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !=/favicon.ico
    RewriteRule ^ index.html [L]
  </IfModule>
</Directory>

#
# Site directory
#
<Directory /usr/local/apache2/htdocs/ancientworld/search>
    Options Indexes Includes FollowSymLinks ExecCGI MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all
  # Various rewrite rules.
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^ - [E=protossl]
    RewriteCond %{HTTPS} on
    RewriteRule ^ - [E=protossl:s]
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule "(^|/)\." - [F]
    RewriteBase /ancientworld/search
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !=/favicon.ico
    RewriteRule ^ index.html [L]
  </IfModule>
</Directory>

#
# Site directory
#
<Directory /usr/local/apache2/htdocs/ancientworld/subject>
  Options Indexes Includes FollowSymLinks ExecCGI MultiViews
  AllowOverride All
  Order allow,deny
  Allow from all
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^ - [E=protossl]
    RewriteCond %{HTTPS} on
    RewriteRule ^ - [E=protossl:s]
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule "(^|/)\." - [F]
    RewriteBase /ancientworld/subject
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !=/favicon.ico
    RewriteRule ^ index.html [L]
  </IfModule>
</Directory>

#
# Site directory
#
<Directory /usr/local/apache2/htdocs/ancientworld/books>
  Options Indexes Includes FollowSymLinks ExecCGI MultiViews
  AllowOverride All
  Order allow,deny
  Allow from all
  <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule ^ - [E=protossl]
    RewriteCond %{HTTPS} on
    RewriteRule ^ - [E=protossl:s]
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteRule "(^|/)\." - [F]
    RewriteBase /ancientworld/books
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !=/favicon.ico
    RewriteRule ^ index.html [L]
  </IfModule>
</Directory>
